name: Sheell Commands

on: [push]

jobs:
  run-shell-command:
  steps:
    - name: echo a string
      run: echo "hello dude"
    - name: multiline string
      run: |
        node -v
        npm -v
        